version: '3'
services:
  rails: &app_base
    build:
      context: .
      dockerfile: "Dockerfile"
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    env_file:
      - "./.env.dev"
    volumes:
      - ".:/app"
      - "bundle:/usr/local/bundle"
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      - SELENIUM_REMOTE_HOST=firefox
  spring:
    <<: *app_base
    command: ["bundle", "exec", "spring", "server"]
    ports: []
    tty: false
    stdin_open: false
  db:
    image: "postgres:10"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - "db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
volumes:
  db:
  bundle:
